apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main # pipelineRun name
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]" # Trigger the pipelineRun on push events on branch main
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone, 
    https://raw.githubusercontent.com/stakater-tekton-catalog/create-git-tag/0.0.12/task/stakater-create-git-tag/stakater-create-git-tag.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/code-linting-mvn/0.0.4/task/stakater-code-linting/stakater-code-linting.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/kube-linting/0.0.10/task/stakater-kube-linting/stakater-kube-linting.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/unit-test/0.0.6/task/stakater-unit-test/stakater-unit-test.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/buildah/0.0.37/task/stakater-buildah/stakater-buildah.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/trivy-scan/0.0.5/task/stakater-trivy-scan/stakater-trivy-scan.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/checkov-scan/0.0.4/task/stakater-checkov-scan/stakater-checkov-scan.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/helm-push/0.0.18/task/stakater-helm-push/stakater-helm-push.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/github-update-cd-repo/0.0.18/task/stakater-github-update-cd-repo/stakater-github-update-cd-repo.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/push-main-tag/0.0.12/task/stakater-push-main-tag/stakater-push-main-tag.yaml]" # The task will be fetched from Tekton Hub. We can also provide direct links to yaml files
    pipelinesascode.tekton.dev/max-keep-runs: "2" # Only remain 2 latest pipelineRuns on SAAP
spec:
  params:
    - name: repo_url
      value: "{{body.repository.ssh_url}}"
    - name: git_revision
      value: "{{revision}}"
    - name: repo_name
      value: "{{repo_name}}" # Dynamic varaible to fetch repo name
    - name: repo_path
      value: "review-web"
    - name: git_branch
      value: "{{source_branch}}"
    - name: organization
      value: "{{body.organization.login}}"
    - name: pr_commit_sha
      value: "{{body.after}}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: git_revision
      - name: repo_path
      - name: organization
      - name: git_branch
    workspaces:
      - name: source
      - name: ssh-directory
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory
        params:
          - name: depth
            value: "0"
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.git_revision)
      - name: create-git-tag
        runAfter:
          - fetch-repository
        taskRef:
          name: stakater-create-git-tag
          kind: Task
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: GIT_REVISION
            value: $(params.git_revision)
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory
      - name: code-linting
        runAfter:
          - create-git-tag
        taskRef:
          name: stakater-code-linting
          kind: Task
        workspaces:
          - name: source
            workspace: source
      - name: kube-linting
        runAfter:
          - create-git-tag
        taskRef:
          name: stakater-kube-linting
          kind: Task
        params:
          - name: FILE
            value: manifest.yaml
          - name: DEPLOYMENT_FILES_PATH
            value: deploy
        workspaces:
          - name: source
            workspace: source
      - name: buildah
        runAfter:
          - kube-linting
        taskRef:
          name: stakater-buildah
          kind: Task
        params:
          - name: IMAGE_NAME
            value: $(params.repo_path):$(tasks.create-git-tag.results.GIT_TAG)
          - name: TLSVERIFY
            value: "false"
          - name: FORMAT
            value: "docker"
          - name: BUILD_IMAGE
            value: "true"
          - name: CURRENT_GIT_TAG
            value: $(tasks.create-git-tag.results.CURRENT_GIT_TAG)
          - name: REPO_NAME
            value: $(params.repo_path)
        workspaces:
          - name: source
            workspace: source
      - name: trivy-scan
        runAfter:
          - buildah
        taskRef:
          name: stakater-trivy-scan
          kind: Task
        params:
          - name: IMAGE_NAME
            value: $(params.repo_path):$(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source
      - name: checkov-scan
        runAfter:
          - buildah
        taskRef:
          name: stakater-checkov-scan
          kind: Task
        workspaces:
          - name: source
            workspace: source
      - name: helm-push
        runAfter:
          - trivy-scan
          - checkov-scan
        taskRef:
          name: stakater-helm-push
          kind: Task
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: REPO_PATH
            value: $(params.repo_path)
          - name: GIT_REVISION
            value: $(params.git_revision)
          - name: SEM_VER
            value: $(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source
      - name: update-cd-repo
        runAfter:
          - helm-push
        taskRef:
          kind: Task
          name: stakater-github-update-cd-repo
        params:
          - name: PULL_REQUEST_COMMITS_API # Replace when not using Git
            value: https://api.github.com/repos/$(params.organization)/$(params.repo_name)/commits/$(params.pr_commit_sha)/pulls
          - name: IMAGE_TAG
            value: $(tasks.create-git-tag.results.GIT_TAG)
          - name: IMAGE_NAME
            value: '$(params.repo_path)'
          - name: PR_NUMBER
            value: "NA"
          - name: REPO_PATH
            value: $(params.repo_path)
          - name: GIT_REVISION
            value: main
          - name: ENVIRONMENT
            value: dev
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: cd-ssh-creds
          - name: repo-token
            workspace: repo-token
      - name: push-main-tag
        runAfter:
          - update-cd-repo
        taskRef:
          kind: Task
          name: stakater-push-main-tag
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: GIT_REVISION
            value: $(params.git_revision)
          - name: IMAGE_TAG
            value: $(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    - name: ssh-directory
      secret:
        secretName: git-ssh-creds
    - name: repo-token
      secret:
        secretName: git-pat-creds
    - name: cd-ssh-creds
      secret:
        secretName: git-ssh-creds
