apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main-review-web
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone, 
    https://raw.githubusercontent.com/stakater-tekton-catalog/create-git-tag/0.0.12/task/stakater-create-git-tag/stakater-create-git-tag.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/buildah/0.0.37/task/stakater-buildah/stakater-buildah.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/helm-push/0.0.18/task/stakater-helm-push/stakater-helm-push.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/github-update-cd-repo/0.0.17/task/stakater-github-update-cd-repo/stakater-github-update-cd-repo.yaml,
    https://raw.githubusercontent.com/stakater-tekton-catalog/push-main-tag/0.0.12/task/stakater-push-main-tag/stakater-push-main-tag.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"

spec:
  params:
    - name: repo_url
      value: {{body.repository.ssh_url}}
    - name: git_revision
      value: {{revision}}
    - name: repo_path
      value: {{repo_name}}
    - name: git_branch
      value: {{source_branch}}
    - name: organization
      value: {{body.repository.owner.name}}
  pipelineSpec:
    params:
      - name: repo_url
      - name: git_revision
      - name: repo_path
      - name: organization
      - name: git_branch
    workspaces:
      - name: source
      - name: ssh-directory

    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory
        params:
          - name: depth
            value: "0"
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.git_revision)

      - name: create-git-tag
        runAfter:
          - fetch-repository
        taskRef:
          name: stakater-create-git-tag
          kind: Task
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: GIT_REVISION
            value: $(params.git_revision)
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory

  

      - name: buildah
        runAfter:
          - create-git-tag
        taskRef:
          name: stakater-buildah
          kind: Task
        params:
          - name: IMAGE_NAME
            value: $(params.repo_path):$(tasks.create-git-tag.results.GIT_TAG)
          - name: TLSVERIFY
            value: "false"
          - name: FORMAT
            value: "docker"
          - name: BUILD_IMAGE
            value: "true"
          - name: CURRENT_GIT_TAG
            value: $(tasks.create-git-tag.results.CURRENT_GIT_TAG)
          - name: REPO_NAME
            value: $(params.repo_path)
        workspaces:
          - name: source
            workspace: source

     
      - name: helm-push
        runAfter:
          - buildah
        taskRef:
          name: stakater-helm-push
          kind: Task
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: REPO_PATH
            value: $(params.repo_path)
          - name: GIT_REVISION
            value: $(params.git_revision)
          - name: SEM_VER
            value: $(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source
            
      - name: update-cd-repo
        runAfter:
          - helm-push
        taskRef:
          kind: Task
          name: stakater-github-update-cd-repo
        params:
          - name: IMAGE_TAG
            value: $(tasks.create-git-tag.results.GIT_TAG)
          - name: IMAGE_NAME
            value: '$(params.repo_path)'
          - name: PR_NUMBER
            value: "NA"
          - name: REPO_PATH
            value: $(params.repo_path)
          - name: GIT_REVISION
            value: main
          - name: NAMESPACE
            value: arsenal-dev
          - name: ENVIRONMENT
            value: dev
          - name: HELM_REGISTRY
            value: 'NA'
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory

      - name: push-main-tag
        runAfter:
          - update-cd-repo
        taskRef:
          kind: Task
          name: stakater-push-main-tag
        params:
          - name: PR_NUMBER
            value: "NA"
          - name: GIT_REVISION
            value: $(params.git_revision)
          - name: IMAGE_TAG
            value: $(tasks.create-git-tag.results.GIT_TAG)
        workspaces:
          - name: source
            workspace: source
          - name: ssh-directory
            workspace: ssh-directory

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: ssh-directory
      secret:
        secretName: git-ssh-creds
